### ISSUE TITLE
write function

### ISSUE THREAD

**Issue by nick-youngblut** [UBod/msa#15]
The msa package seems to lack a function for writing the alignment to a fasta file. The `msaPrettyPrint()` function will write to a file, but I just want to write the alignment and not print it.

**Comment by nick-youngblut** [comment]
I see that `msaPrettyPrint()` basically just does the following when writing: 

```
writeXStringSet(as(unmasked(aln), "XStringSet"), file="output.fasta")
```

It would be helpful to have a convenience function that runs that code.

**Comment by UBod** [comment]
Thanks for your suggestion! I will think about it for the next release (or whether I consider it sufficient to explicitly mention how to write an alignment to a FASTA with the method you mentioned).
