### ISSUE TITLE
Use of my own .aln ?

### ISSUE THREAD

**Issue by dplazas** [UBod/msa#18]
Hi,
sorted sorry

**Comment by UBod** [comment]
Does 'sorted' mean that you already solved the issue?
In any case, I would have suggested to read the .aln file using seqinr's read.alignment() function and then to convert the alignment object to an AAMultipleAlignment object. msaPrettyPrint() requires some sort of MultipleAlignment object.

**Comment by dplazas** [comment]
Hi, 
that's correct, I am sorry. Anyway I will write down your suggestion for future analyses. Finally, it would be great to have MAFFT incorporated. Thanks for your help!

**Comment by UBod** [comment]
I agree that the incorpation of additional multiple sequence alignment methods would be great. However, this is a major endeavor, and unfortunately it is hard to find volunteers/students to do that.
