### ISSUE TITLE
msaClustalOmega(percentId = TRUE) percentage identity values not available?

### ISSUE THREAD

**Issue by Ni-Ar** [UBod/msa#25]
Hi, 

I import an aligned (with gaps) fasta file with multipled sequences
```R
dna_afa <- readDNAStringSet(filepath = dna_alg_path, format = 'fasta', use.names = T)
```
I use clustalOmega to calculate a percentage of identity matrix with
```R
pim <- msaClustalOmega(inputSeqs = dna_afa, type = 'dna', full = TRUE,  order = 'input', percentId = TRUE, 
threads = 1,  verbose = T)
```

The verbose output is:
```R
params: clustalo --R -o tempClustalOmega.aln --outfmt=clustal --seqtype=dna --force --gapopen=6.000000 --gapext=1.000000 --cluster-size=100 --iter=0 --threads=1 --output-order=input-order --full --percent-id --version
using Gonnet
1.2.0

Error: ClustalOmegaException (0)

Using 1 threads
Reading sequence file from R
Read 153 sequences (type: DNA) from sequences_from_R
Input sequences are aligned. Will turn alignment into HMM and add it to the user provided background HMMs.
Calculating pairwise aligned identity distances...
Pairwise identity calculation progress done. CPU time: 0.02u 0.00s 00:00:00.02 Elapsed: 00:00:00
Guide-tree computation done.
Progressive alignment progress done. CPU time: 0.66u 0.05s 00:00:00.71 Elapsed: 00:00:01
```

What I would want to do can be achieved by command line with:
```shell
clustalo --infile path/to/file.afa --distmat-out path/to/file.pim --percent-id --full
```

Now in the R  if I do:

```R
class(pim)
[1] "MsaDNAMultipleAlignment"
attr(,"package")
[1] "msa"
```

how can I extract the actual percentage identity in the pairwise comparisons?
Could it be that this is related to `Error: ClustalOmegaException (0)`?

Thanks
```R
 R.version.string
[1] "R version 4.1.2 (2021-11-01)"
```

```R
packageVersion("msa")
[1] ‘1.26.0’
```

**Comment by UBod** [comment]
Hi @Ni-Ar, thanks for reporting this issue! Here are my comments:

1. Your version of the package seems to be quite old. I tried to re-run your code and did not receive any ClustalOmega error. I have to say, though, that I did not have your original sequences. So it might be necessary to have your sequences to find out whether I can reproduce the error.
2. ClustalOmega is not supposed to re-align already aligned sequences. It seems that ClustalOmega tolerates this, but this is not the right approach.
3. All three algorithms of the `msa` package are only supported for aligning sequences. Additional functionality implemented in the original software packages `ClustalW`, `ClustalOmega`, and `Muscle` beyond multiple sequence alignment (e.g. extracting of guide trees, computation of phylogenetic trees, or the distance matrix calculation that you would need) **_cannot_** be accessed through the interface of the `msa` package. Sorry!

**Comment by Ni-Ar** [comment]
Hey,

1. I'll try to update it and see what happens.
2. My goal wasn't to re-align but just to do the pairwise comparison of sequence similarity. 
3. Got it, wasn't aware of this. If `percentId = TRUE` parameter is implemented in the R function why it is not supported?

Are you aware of alternatives for calculating sequence similarities (or similar things)  in R from an already aligned fasta file (or align then seq. similarity)?

Thanks a lot

**Comment by UBod** [comment]
1. Great!
2. Sure, I was aware of that. I just wanted to mention that the algorithm is made for aligning non-aligned sequences. But I understand that you used it like that in order to access other features of ClustalOmega.
3. Thanks for pointing out this issue! I suppose that was a misunderstanding, so the developers actually forward an otherwise irrelevant parameter to the underlying library. I will check that and possibly change it in a future version.

Yes, there are methods implemented in R packages for computing distances/similarities of sequences based on multiple alignments. As a first pointer, see Section 6.3 "Interfacing to Other Packages" in the package vignette. I suppose the `seqinr` package is a good start.
