### ISSUE TITLE
*** ERROR ***  MSA::SetIdCount: cannot increase count

### ISSUE THREAD

**Issue by moa4020** [UBod/msa#32]
Using msa for aligning more than 2000 sequences of approximate length 61 nucleotides. 

msa version 1.34.0

`library(Biostrings)`
`sequenceList <- paste0(readDNAStringSet(filepath="msaTroubleshootExample.TAR.DNA.n2259.fasta"))`
`msa_seqs <- msa(sequenceList, method = "Muscle")`

[msaTroubleshootExample.TAR.DNA.n2259.fasta.zip](https://github.com/user-attachments/files/17682905/msaTroubleshootExample.TAR.DNA.n2259.fasta.zip)

**Comment by UBod** [comment]
This error should have been solved in version 1.37.3. It appears when you run Muscle for a second with a larger number of sequences than at the first time. So either upgrade to a newer version of `msa` or make sure that you always run Muscle with a new R session. In any case, I'd rather recommend using ClustalOmega if you wish to align larger number of sequences.
