### ISSUE TITLE
object 'msaClustalW' of mode 'function' was not found

### ISSUE THREAD

**Issue by richelbilderbeek** [UBod/msa#4]
Posted the question and workaround [here](https://support.bioconductor.org/p/133439/): adding namespaces to some functions will fix this.

Reply from @UBod here:

> Thanks for your kind willingness to volunteer, and sorry for the excessively late reply! Yes, that would be great. One approach would be that you checkout the latest version from Github (https://github.com/UBod/msa), make your changes and create a pull request. If it’s only about that single line … the call to the MSA algorithms in the convenience function msa() (line 22 of https://github.com/UBod/msa/blob/master/R/msa.R), then I can also do it, which would keep the organizational overhead low. So please let me know if there are any other issues. If so, please create a pull request. If it’s only about that single line, I will fix this within the next few days.

Although I cannot assign myself to this, I will do this Issue :+1:

**Comment by richelbilderbeek** [comment]
To quote myself, from [the bioconductor forum](https://support.bioconductor.org/p/133439/):

I found the help for the msa::msa funcion (?msa::msa) and ran the first example code:

```r
filepath <- system.file("examples", "exampleAA.fasta", package="msa")
mySeqs <- Biostrings::readAAStringSet(filepath)
msa::msa(mySeqs)    
```

The error I got was:

```r
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'msaClustalW' of mode 'function' was not found
```

**Comment by richelbilderbeek** [comment]
Again, the reason was that not all `msa` function calls are prefixed with `msa::` when within `msa` functions.

**Comment by richelbilderbeek** [comment]
Copy-paste friendly oneliner to reproduce bug:

```r
detach("package:msa"); msa::msa(Biostrings::readAAStringSet(system.file("examples", "exampleAA.fasta", package="msa"))) 
```

**Comment by richelbilderbeek** [comment]
I got it to work:

```
> detach("package:msa"); msa::msa(Biostrings::readAAStringSet(system.file("examples", "exampleAA.fasta", package="msa")), method="ClustalW")    
use default substitution matrix
CLUSTAL 2.1  

Call:
   msa::msa(Biostrings::readAAStringSet(system.file("examples",     "exampleAA.fasta", package = "msa")), method = "ClustalW")

MsaAAMultipleAlignment with 9 rows and 456 columns
    aln                                                            names
[1] MAAVVLENGVLSRKLSDFGQETSYIEDNSN...DNTQQLKILADSINSEVGILCNALQKIKS PH4H_Rattus_norve...
[2] MAAVVLENGVLSRKLSDFGQETSYIEDNSN...DNTQQLKILADSINSEVGILCHALQKIKS PH4H_Mus_musculus
[3] MSTAVLENPGLGRKLSDFGQETSYIEDNCN...DNTQQLKILADSINSEIGILCSALQKIK- PH4H_Homo_sapiens
[4] MSALVLESRALGRKLSDFGQETSYIEGNSD...DNTQQLKILADSISSEVEILCSALQKLK- PH4H_Bos_taurus
[5] ------------------------------...DDLVLNAGDRQGWADTEDV---------- PH4H_Chromobacter...
[6] ------------------------------...GDAVLNAGTREGWADTADI---------- PH4H_Ralstonia_so...
[7] ------------------------------...GDAVLTRGT-QAYATAGGRLAGAAAG--- PH4H_Caulobacter_...
[8] ------------------------------...KQAA------------------------- PH4H_Pseudomonas_...
[9] ------------------------------...----------------------------- PH4H_Rhizobium_loti
Con ------------------------------...D?????????????????IL??A???--- Consensus 
```

**Comment by richelbilderbeek** [comment]
Hi @UBod.

I have attempted to get a function call to `msa::msa` to work without having the library loaded:

```r
library(msa); detach("package:msa"); msa::msa(Biostrings::readAAStringSet(system.file("examples", "exampleAA.fasta", package="msa")), method="ClustalW")    
```

(note that `library(msa); detach("package:msa"); ` is just a copy-paste friendly version to make sure `msa` is not loaded)

The original error message was the following:

```
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'msaClustalW' of mode 'function' was not found
```

The error message is given because `msa::msa` calls `msaClustalW`, instead of `msa::msaClustalW`.

I have gotten it to work (you can see my attempt [here](https://github.com/richelbilderbeek/msa/blame/master/R/msa.R#L21)), but bumped into an architectural problem: `msa::msa` can be called with multiple `method`s (yet, sure, in the end, only one is used). I am unsure if `match.fun` *can* work without loading the library.

After this attempt, I hope I can still accept your offer that you do so, as you claimed it would be easy. Apparently, you have some skills that I lack :+1: 

Will you take over to get to run the code snippet above?

Cheers, Richel

**Comment by richelbilderbeek** [comment]
I'll be working on this, on the `develop` branch :+1:

**Comment by UBod** [comment]
Finally, after a long time, I included a fix in the package (pushed also to BioC devel). However, I adopted a slightly different way of solving this: instead of a chain of if/else if/else conditionals, I used get(). See R/msa.R. Once the checks on the BioC servers are finished successfully, I will close this issue.

**Comment by UBod** [comment]
Build and check is running smoothly with the new version (1.31.2 on the BioC devel branch). So I am closing this issue and also the  [related one](https://github.com/UBod/msa/issues/5).
