### ISSUE TITLE
Cannot load library silently

### ISSUE THREAD

**Issue by richelbilderbeek** [UBod/msa#5]
At [the Bionconductor forum I posted this](https://support.bioconductor.org/p/133577/).

Reply from @UBod:

> Thanks for your kind willingness to volunteer, and sorry for the excessively late reply! Yes, that would be great. One approach would be that you checkout the latest version from Github (https://github.com/UBod/msa), make your changes and create a pull request. If it’s only about that single line … the call to the MSA algorithms in the convenience function msa() (line 22 of https://github.com/UBod/msa/blob/master/R/msa.R), then I can also do it, which would keep the organizational overhead low. So please let me know if there are any other issues. If so, please create a pull request. If it’s only about that single line, I will fix this within the next few days.

So I will fix this one as well :+1:

**Comment by UBod** [comment]
Build and check is running smoothly with the new version (1.31.2 on the BioC devel branch). So I am closing this issue and also the [related one](https://github.com/UBod/msa/issues/4).
