### ISSUE TITLE
Bug report: msa::msaConvert to seqinr format results in incorrect FASTA file

### ISSUE THREAD

**Issue by richelbilderbeek** [UBod/msa#6]
Dear prof Bodenhofer, hello @UBod,

Here I submit a reproducible example of a bug report that proves that a call to `msa::msaConvert` to convert an `msa` alignment to `seqinr` format results in something that `seqinr` cannot store properly. After that I post my `sessionInfo`.

The example is somewhat elaborate, as I first demonstrate that `seqinr` is not to blame. In short:

 * create an alignment as FASTA file text
 * save and load it using `seqinr`, to prove `seqinr` works as expected
 * create a multiple sequence alignment using `msa::msa` 
 * convert the multiple sequence alignment to `seqinr` format
 * save and load it using `seqinr`, to prove that the conversion to `seqinr` format went wrong somewhere

I discovered this bug due to [a similar bug in bios2mds](https://github.com/richelbilderbeek/reports/issues/1).

Of course, I may have misunderstood something, even though the documentation of `msa::msaConvert` is quite clear. Additionally, I would be help to help verify if this is fixed :+1:

Good luck, Richel Bilderbeek

```r
library(msa)
library(testhat)

# This is the FASTA text of the protein sequences we work on
fasta_text <- c(
  ">A",
  "TIGSFQFGYNTGVINAPEKIIKEFITKTLTD",
  ">B",
  "IGSFQFGYNTGVINAPEKIIKEFITKTLT"
)

# Save it to a file
fasta_filename <- tempfile()
readr::write_lines(x = fasta_text, file = fasta_filename)

# Of course, reading that file results in the original FASTA file text
expect_equal(
  readr::read_lines(file = fasta_filename),
  fasta_text
)

##################################################
# Here we prove that the problem is not in seqinr
##################################################
#
# Now we load the file again using seqinr
alignment <- seqinr::read.fasta(file = fasta_filename, seqtype = "AA")

# The alignment has the correct lengths
expect_equal(length(alignment$A), nchar(fasta_text[2]))
expect_equal(length(alignment$B), nchar(fasta_text[4]))

# Now we save that alignment again to a FASTA file using seqinr
seqinr::write.fasta(
  sequences = alignment,
  names = names(alignment),
  file.out = fasta_filename
)

# Great, saving and loading with seqinr works!
expect_equal(
  readr::read_lines(file = fasta_filename),
  fasta_text
)

############################################################
# Here we save and load an alignment after calling msa::msa
############################################################
alignment <- msa::msa(
  inputSeqs = Biostrings::readAAStringSet(fasta_filename)
)

# The alignment is correct
expect_equal(unname(as.character(alignment)[1]), fasta_text[2])
expect_equal(
  unname(as.character(alignment)[2]),
  paste0("-", fasta_text[4], "-") # Indeed, the second sequence was shorter
)

# Convert the alignment to seqinr format, works great!
msa_as_seqinr_alignment <- msa::msaConvert(alignment, "seqinr::alignment")
expect_equal(msa_as_seqinr_alignment$seq[1], fasta_text[2])
expect_equal(
  msa_as_seqinr_alignment$seq[2],
  paste0("-", fasta_text[4], "-") # Indeed, the second sequence was shorter
)

# Save to file, here things go wrong
seqinr::write.fasta(
  sequences = msa_as_seqinr_alignment$seq,
  names = names(sequences),
  file.out = fasta_filename
)

# Hand-craft the aligned FASTA text
# (note that this does not matter much for this bug)
aligned_fasta_text <- fasta_text
aligned_fasta_text[4] <- paste0("-", fasta_text[4], "-")

# The saved file has only three lines
#
# Error: readr::read_lines(file = fasta_filename) not equal to `fasta_text`.
# Lengths differ: 3 is not 4
#
# Printing the saved file shows the problem:
#
# > readr::read_lines(file = fasta_filename)
# [1] ">A"
# [2] ">B"
# [3] "TIGSFQFGYNTGVINAPEKIIKEFITKTLTD-IGSFQFGYNTGVINAPEKIIKEFITKTLT-"
#
# The problem is that the two sequences are both saved at the end, in one line
#
expect_equal(
  readr::read_lines(file = fasta_filename),
  aligned_fasta_text
)
```

My session info:

```r
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] seqinr_4.2-4        ncbi_0.0.0.9000     msa_1.18.0          Biostrings_2.54.0  
[5] XVector_0.26.0      IRanges_2.20.2      S4Vectors_0.24.4    BiocGenerics_0.32.0
[9] testthat_2.3.2     

loaded via a namespace (and not attached):
 [1] fs_1.5.0                usethis_1.6.3           devtools_2.3.2          webshot_0.5.2          
 [5] httr_1.4.2              rprojroot_1.3-2         tools_3.6.3             backports_1.1.10       
 [9] R6_2.4.1                colorspace_1.4-1        ade4_1.7-15             manipulateWidget_0.10.1
[13] withr_2.3.0             prettyunits_1.1.1       processx_3.4.4          curl_4.3               
[17] compiler_3.6.3          git2r_0.27.1            cli_2.1.0               desc_1.2.0             
[21] scales_1.1.1            readr_1.4.0             Peptides_2.4.2          callr_3.5.1            
[25] stringr_1.4.0           digest_0.6.27           rentrez_1.2.2           pkgconfig_2.0.3        
[29] htmltools_0.5.0.9001    sessioninfo_1.1.1       fastmap_1.0.1           htmlwidgets_1.5.2      
[33] rlang_0.4.8             rstudioapi_0.11         shiny_1.5.0             jsonlite_1.7.1         
[37] crosstalk_1.1.0.1       magrittr_1.5            Rcpp_1.0.5              munsell_0.5.0          
[41] fansi_0.4.1             lifecycle_0.2.0         stringi_1.5.3           whisker_0.4            
[45] MASS_7.3-51.5           zlibbioc_1.32.0         pkgbuild_1.1.0          grid_3.6.3             
[49] promises_1.1.1          crayon_1.3.4            miniUI_0.1.1.1          beautier_2.4           
[53] hms_0.5.3               knitr_1.30              ps_1.4.0                pillar_1.4.6           
[57] pkgload_1.1.0           XML_3.99-0.3            glue_1.4.2              bios2mds_1.2.3         
[61] remotes_2.2.0           vctrs_0.3.4             httpuv_1.5.4            amap_0.8-18            
[65] assertthat_0.2.1        bio3d_2.4-1             xfun_0.18               mime_0.9               
[69] xtable_1.8-4            e1071_1.7-4             later_1.1.0.1           class_7.3-15           
[73] tibble_3.0.4            memoise_1.1.0           cluster_2.1.0           rgl_0.100.54           
[77] ellipsis_0.3.1         
```

**Comment by UBod** [comment]
I now checked this issue after having forgotten about it for an excessive period of time ... SORRY!
The issue is based on a misconception: the function `msaConvert()` with `type="seqinr::alignment"` is not meant to produce a sequence object as used by the seqinr package, but an alignment (class `alignment` in `seqinr`). This class cannot be written to FASTA files directly using the `write.fasta()` function.

**Comment by richelbilderbeek** [comment]
Hi @UBod, 

Thanks for taking a second look!

I agree with your reasoning, which takes me to the next point:

The problem is not that things work or don't, the problem is that `write.fasta` gives the **illusion** it works. 
I suggest to give an error message when it shouldn't work. Below I give the test code:

```r
library(msa)
library(testhat)

# This is the FASTA text of the protein sequences we work on
fasta_text <- c(
  ">A",
  "TIGSFQFGYNTGVINAPEKIIKEFITKTLTD",
  ">B",
  "IGSFQFGYNTGVINAPEKIIKEFITKTLT"
)

alignment <- msa::msa(
  inputSeqs = Biostrings::readAAStringSet(fasta_filename)
)

# Convert the alignment to seqinr format, works great!
msa_as_seqinr_alignment <- msa::msaConvert(alignment, "seqinr::alignment")

# Save to file, here things go wrong
expect_error(
  seqinr::write.fasta(
    sequences = msa_as_seqinr_alignment$seq,
    names = names(sequences),
    file.out = fasta_filename
  ),
  "'sequences' must be of type .*, not of type 'seqinr::alignment'"
)
```

Having that, or a similar, error message would have saved me hours of works. I hope it will be added, for me and other users.

Would be great!

**Comment by UBod** [comment]
Thanks for coming back to this issue, @richelbilderbeek! I understand your point, but that is something out of the scope of my package, if I am not mistaken. `msa `correctly converts to an object of class `alignment`. We cannot foresee that somebody might apply the `write.fasta()` function from a different package to it. I think that is supposed to be dealt with by the `seqinr `package, or am I missing something here?

**Comment by richelbilderbeek** [comment]
> or am I missing something here?

No, maybe not, yet I just needed to ask. If, for example, the `class` of the supported classes can be read, then a simple `if`/`stopifnot` will help. Doing a full probe of the object would -indeed- be excessive.

So:
 
 * if easy fix: yes, fix would be great. 
 * if no easy fix, it's OK as it is. 

It is a choice to protect against Murphy or Machiavelli :-)

**Comment by UBod** [comment]
Sorry, I do not get the point. What do you mean by "... the class of the supported classes can be read, then a simple if/stopifnot will help"? Once again, this is the situation as it appears to me:

- The `seqinr` package uses multiple types of data, among others, sets of sequences (in the package realized as lists of objects of type `SeqFastAA` or `SeqFastadna`) and alignments.
- My package `msa` can convert multiple sequences alignments to the class `alignment` as defined and used by the `seqinr` package.
- The `seqinr` package contains a function `write.fasta()` that produces a malformed FASTA file when being applied erroneously to an object of class `alignment`.
- So what should the `msa` package do differently in order to prevent that situation? The only solution would be that the `write.fasta()` function in the `seqinr` package makes better input checks, no?

**Comment by richelbilderbeek** [comment]
First, thanks so much for your time!

> The only solution would be that the write.fasta() function in the seqinr package makes better input checks, no?

Agreed, if the check is cheap. And -thanks to your answer!- I can conclude it is.

So, I suggest to add the following if statement at the start of `write.fasta`:

```r
write.fasta <- function(
    sequences = # ...
  )
{
  if (!inherits(sequences, "SeqFastAA") && !inherits(sequences, "SeqFastadna")) {
    stop("'sequences' must be of class 'SeqFastAA' or 'SeqFastadna'")
  }
  # Original code
}
```

Would you agree that the added `if` is worth it? 

If yes, I'd be happy to add it, together with some proper tests :-)

**Comment by UBod** [comment]
Agreed, but I am not a developer of the `seqinr` package, so I am not in the position to do that. Please write to the maintainers of the `seqinr` package. There is even a mailing list for seqinr-related discussions: [https://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/seqinr-forum](https://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/seqinr-forum)
