### ISSUE TITLE
Interpreting the output of msaConsensusSequence

### ISSUE THREAD

**Issue by padpadpadpad** [UBod/msa#9]
Hi

Thanks for the amazing package. Just wondering if you could point me to where the information for interpreting the output of `msaConsensusSequence` is.

Speciifcally what the `?` and the `-` mean.

An example would be

`------ATGCCGACG??GATCCAGAACAACTTCCGCGT?CGGAAGA?CTTCGCGAAGATC???AAGATC`

Many thanks

**Comment by UBod** [comment]
All non-?-symbols refer to the most frequent symbol in this column of the multiple sequence alignment. So, if you see a dash '-', it means that most sequences have a gap in the alignment at this position. If you see an 'A', it means that most sequences have an 'A' at this position, and so forth. A question mark '?' means that there is a large variation of symbols in the alignments at this position, i.e. no clear majority in favor of one symbol. I hope that helps.
